#' Hello function
#'
#' This function demonstrates different functionalities based on the input.
#'
#' @param x A character specifying the mode of operation: 'ct' for central tendency,
#'          'df' for data entry and presentation, 'mo' for mathematical operations.
#'          Default is NULL.
#'
#' @examples
#' hello("ct")
#' hello("df")
#' hello("mo")
#'
#' @export
hello <- function(x = NULL) {
  if (!is.null(x)) {
    if (is.character(x)) {
      if (x == "ct") {
        cat("# Measure of central tendency & dispersions.\n",
            "x <- c(12,13,14,15,16,17,25,32,39)\n",
            "mean_of_x <- mean(x)\n",
            "print(mean_of_x)\n",
            "#--------\n",
            "median_of_x <- median(x)\n",
            "print(median_of_x)\n",
            "calculate_mode <- function(x) {\n",
            "  freq_table <- table(x)\n",
            "  mode <- names(freq_table)[freq_table == max(freq_table)]\n",
            "  return(mode)\n",
            "}\n",
            "#--------\n",
            "mode_of_x <- calculate_mode(x)\n",
            "print(mode_of_x)\n",
            "#--------\n",
            "variance_of_x <- var(x)\n",
            "print(variance_of_x)\n",
            "#--------\n",
            "std_deviation <- sd(x)\n",
            "print(std_deviation)\n",
            "#--------\n",
            "interquartile_range <- IQR(x)\n",
            "print(interquartile_range)\n",
            "#--------\n",
            "range1 <- max(x) - min(x)\n",
            "print(range1)\n")
      } else if (x == "df") {
        cat("# Data Entry and presentation function.\n",
            "# Create dataframe with information\n",
            "info=data.frame(id=c(1,1,2,3),name=c('d','k','m','c'),age=c(10,12,13,11))\n",
            "info\n\n",
            "# Import in-built packages\n",
            "data=mtcars\n",
            "data\n\n",
            "# Boxplot\n",
            "boxplot(info$id)\n",
            "boxplot(mtcars$mpg,\n",
            "        main='Boxplot of mpg',\n",
            "        ylab='mpg',\n",
            "        col='green',\n",
            "        border='red')\n\n",
            "# Histogram\n",
            "hist(info$id)\n",
            "hist(mtcars$mpg)\n\n",
            "# Scatter plot\n",
            "plot(mtcars$mpg, mtcars$hp)\n\n",
            "# Barplot\n",
            "barplot(info$age)\n\n",
            "# Pie chart\n",
            "pie(info$id)\n\n",
            "# Print uppercase letters\n",
            "print(LETTERS)\n\n",
            "# Print class of variables\n",
            "x=12\n",
            "print(class(x))\n",
            "print(class('True'))\n",
            "print(class(TRUE))\n")
      } else if (x == "mo") {
        cat("# Mathematical Operations & functions\n",
            "# Arithmetic operations--------------\n\n",
            "x = 2\n",
            "y = 3\n\n",
            "x + y\n",
            "x - y\n",
            "x / y\n",
            "x %% y\n",
            "x * y\n",
            "x**y\n",
            "x ^ y\n\n",
            "# Math Functions-------------------\n\n",
            "# Maximum value\n",
            "max(8, 99, 15)\n\n",
            "# Minimum value\n",
            "min(8, 99, 15)\n\n",
            "# Square root\n",
            "sqrt(81)\n\n",
            "# Absolute value\n",
            "abs(-8.9)\n\n",
            "# Ceiling\n",
            "ceiling(2.6)\n\n",
            "# Floor\n",
            "floor(2.6)\n\n",
            "# Trigonometric functions\n",
            "cos(4)\n",
            "sin(4)\n",
            "tan(4)\n\n",
            "# Logarithm\n",
            "log(4)\n\n",
            "# Exponential function\n",
            "exp(4)\n\n",
            "# Relational Operators------------\n\n",
            "x <- 10\n",
            "y <- 25\n\n",
            "x < y\n",
            "x > y\n",
            "x <= 5\n",
            "y >= 20\n",
            "y == 25\n",
            "x != 10\n\n",
            "# Logical-------------------------------\n\n",
            "x = c(TRUE, FALSE, 0, 6)\n",
            "y = c(FALSE, TRUE, TRUE)\n\n",
            "# Logical NOT\n",
            "!x\n\n",
            "# Logical AND\n",
            "x & y\n\n",
            "# Logical AND (element-wise)\n",
            "x && y\n\n",
            "# Logical OR\n",
            "x | y\n\n",
            "# Logical OR (element-wise)\n",
            "x || y\n\n",
            "# Operation on vectors-------------\n\n",
            "x = c(2,9,4)\n",
            "y = c(6, 5, 1)\n\n",
            "x + y\n",
            "x > y\n")
      } else if (x == "mx") {
        cat("# Matrix And Data Frame Ops & feat.\n",
            "# Matrix\n",
            "A = matrix(c(1,2,3,4,5,6), nrow = 2, ncol =3)\n",
            "A\n",
            "B = matrix(c(9,10,11,12,13,14), nrow = 2, ncol =3)\n",
            "B\n",
            "C=matrix(10:3,nrow = 2,ncol=3)\n",
            "C\n",
            "# add only if same row and col\n",
            "C+A\n",
            "# Multiply with scalar\n",
            "C*2\n\n",
            "# Matrix Multiplication\n",
            "m = matrix(1:8, nrow = 2)\n",
            "n = matrix(8:15, nrow = 4)\n",
            "m %*% n\n\n",
            "# Matrix and find max value and its position\n",
            "m1=matrix(1:12,nrow = 3)\n",
            "m1\n",
            "max_value=max(m1)\n",
            "max_value \n\n",
            "Position_max = which(m1==max_value, arr.ind =TRUE)\n",
            "Position_max\n\n",
            "# dataframe and mean of specific col\n",
            "df=data.frame(Name=c('K','H','D','N','R'),\n",
            "             Age= c(23,22,22,21,22),\n",
            "             Vate= c(TRUE,FALSE,TRUE,TRUE,FALSE))\n",
            "df\n\n",
            "mean_of_age=mean(df$Age)\n",
            "mean_of_age\n\n",
            "# add col\n",
            "df$Grade<-c('A','B','C','D','A')\n",
            "df\n")
      } else if (x == "co") {
        cat("# Pearson Correlation\n",
            "# where,\n",
            "# • x and y: two vectors of length n\n",
            "# • mx and my: corresponds to the means of x and y, respectively.\n",
            "# Note:\n",
            "# • r takes a value between -1 (negative correlation) and 1 (positive correlation).\n",
            "# • r = 0 means no correlation.\n",
            "# • Can not be applied to ordinal variables.\n",
            "# • The sample size should be moderate (20-30) for good estimation.\n",
            "# • Outliers can lead to misleading values means not robust with outliers.\n\n",
            "# Pearson Correlation Testing Using cor()\n",
            "# Vectors with the same length\n",
            "x1 = c(1, 2, 3, 4, 5, 6, 7)\n",
            "y1 = c(1, 3, 6, 2, 7, 4, 5)\n",
            "# Calculating Correlation coefficient Using cor() method\n",
            "result = cor(x1, y1, method = 'pearson')\n",
            "cat('Pearson correlation coefficient is:', result)\n\n",
            "# Pearson Correlation Testing Using cor.test()\n",
            "# Taking two numeric Vectors with the same length\n",
            "x = c(1, 2, 3, 4, 5, 6, 7)\n",
            "y = c(1, 3, 6, 2, 7, 4, 5)\n",
            "# Calculating Correlation coefficient Using cor.test() method\n",
            "result = cor.test(x, y, method = 'pearson')\n",
            "# Print the result\n",
            "print(result)\n\n",
            "# Pearson Correlation Testing\n",
            "# Import data into RStudio\n",
            "df = read.csv('Auto.csv')\n",
            "# Taking two columns\n",
            "# Vectors with the same length\n",
            "x = df$mpg\n",
            "y = df$weight\n",
            "# Calculating Correlation coefficient Using cor() method\n",
            "result = cor(x, y, method = 'pearson')\n",
            "# Print the result\n",
            "cat('Person correlation coefficient is:', result)\n\n",
            "# Using cor.test() method\n",
            "res = cor.test(x, y, method = 'pearson')\n",
            "print(res)\n\n",
            "# From the following data, compute Karl Pearson’s coefficient of correlation.\n",
            "x2=c(10,20,30,40,50,60,70)\n",
            "y2=c(8,6,14,16,10,20,24)\n",
            "resp1=cor.test(price,supply,method='pearson')\n",
            "resp1\n\n",
            "# Interpretation: Since the Pearson coefficient is 0.8504201.\n",
            "# Also p-value is 0.015308 < 0.05. So the null hypothesis is accepted.\n",
            "# So it is statistically reasonable to conclude that there is a significant\n",
            "# positive correlation between the price and supply based on the sample.\n\n",
            "# Compute the Spearman rank correlation.\n",
            "History=c(35,23,47,17,10,43,9,6,28)\n",
            "Algebra=c(30,33,45,23,8,49,12,4,31)\n",
            "ress3=cor.test(History,Algebra,method='spearman')\n",
            "ress3\n\n",
            "# Interpretation: Since the correlation coefficient is 0.9.\n",
            "# Also p-value is 0.0020282 < 0.05. So the null hypothesis is rejected.\n",
            "# So it is statistically reasonable to conclude that there is a significant positive correlation\n",
            "# between the price and supply based on the sample.\n\n",
            "# cov() function to calculate the covariance between two data frames or vectors.\n",
            "a <- c(2,4,6,8,10)\n",
            "b <- c(1,11,3,33,5)\n",
            "print(cov(a, b, method = 'pearson'))\n",
            "# Print covariance using different methods\n",
            "print(cov(a, b))\n",
            "print(cov(a, b, method = 'pearson'))\n",
            "print(cov(a, b, method = 'kendall'))\n",
            "print(cov(a, b, method = 'spearman'))\n")
      } else if (x == "cp") {
        cat("# Conditional Probability\n",
            "# calculate conditional probability using the prop.table() function\n\n",
            "# First, let’s create a simple data frame with the information:\n",
            "# Data frame with weather information\n",
            "weather_data <- data.frame(\n",
            "    Cloudy = c('Yes', 'Yes', 'No', 'No'),\n",
            "    Rain = c('Yes', 'No', 'Yes', 'No'),\n",
            "    Frequency = c(30, 20, 10, 40)\n",
            "  )\n",
            "# let’s calculate the conditional probability\n",
            "# of rain given the presence of clouds (P(Rain | Cloudy)):\n\n",
            "# Total frequency of cloudy days\n",
            "total_cloudy <-\n",
            "  sum(weather_data$Frequency[weather_data$Cloudy == 'Yes'])\n\n",
            "# Frequency of rainy days when it's cloudy\n",
            "rainy_and_cloudy <-\n",
            "  weather_data$Frequency[weather_data$Cloudy == 'Yes' &\n",
            "                           weather_data$Rain == 'Yes']\n\n",
            "# Conditional probability of rain given clouds\n",
            "P_rain_given_cloudy <- rainy_and_cloudy / total_cloudy\n",
            "P_rain_given_cloudy\n\n",
            "# Bayes’ Theorem in R\n",
            "# Suppose we know the following probabilities:\n",
            "# ● P(rain) = 0.20\n",
            "# ● P(cloudy) = 0.40\n",
            "# ● P(cloudy | rain) = 0.85\n",
            "# To calculate P(rain | cloudy), we can use the following syntax:\n\n",
            "# define function for Bayes' Theorem\n",
            "bayesTheorem <- function(pA, pB, pBA) {\n",
            "  pAB <- pA * pBA / pB\n",
            "  return(pAB)\n",
            "}\n\n",
            "# define probabilities\n",
            "pRain <- 0.2\n",
            "pCloudy <- 0.4\n",
            "pCloudyRain <- 0.85\n\n",
            "# use function to calculate conditional probability\n",
            "bayesTheorem(pRain, pCloudy, pCloudyRain)\n\n",
            "# using bayesTheorem()\n",
            "psunny <- 0.65\n",
            "pcloudy <- 0.20\n",
            "pcloudysunny <- 0.30\n",
            "# Let’s make use of the function to calculate the conditional probability\n",
            "bayesTheorem(psunny, pcloudy, pcloudysunny)\n")
      } else if (x == "bp") {
        cat("# BINOMIAL DISTRIBUTION\n",
            "# consider 15 trials with probability of success is 0.6, what is the probability of getting 8 successes\n",
            "p = 0.6\n",
            "n = 15\n",
            "x = 8\n\n",
            "prob_of_8_success = dbinom(x, size = n, prob = p)\n",
            "prob_of_8_success\n",
            "cat('prob_of_8_success', prob_of_8_success)\n\n",
            "# Q2\n",
            "p = 1/4\n",
            "n = 6\n",
            "x = 4\n\n",
            "prob = dbinom(x, size = n, prob = p)\n",
            "prob\n",
            "plot(prob)\n",
            "plot(prob, cdf = TRUE)\n\n",
            "# consider 20 trials with a probability of success is 0.8, what is the probability of at least 15 successes\n",
            "p = 0.8\n",
            "n = 20\n\n",
            "prob = 1 - pbinom(14, size = n, prob = 0.8)  # at least 15 that's why 1 - probability of 14\n",
            "prob\n",
            "# plot\n",
            "plot(x, pbinom(x, size = n, prob = 0.8), main = 'Probability mass function for Bin(13,0.7)')\n\n",
            "# consider 30 trials with a probability of success is 0.4, what is the probability of success between 10-15\n",
            "p = 0.4\n",
            "n = 30\n",
            "lower_bound = 10\n",
            "upper_bound = 15\n",
            "prob_of_lowerbound = pbinom(lower_bound - 1, size = n, prob = p)\n",
            "prob_of_upperbound = pbinom(upper_bound, size = n, prob = p)\n",
            "prob_bet_10_15 = prob_of_upperbound - prob_of_lowerbound\n",
            "prob_bet_10_15\n",
            "# Generate 8 random numbers from 150 with prob=0.4\n",
            "n = 8\n",
            "size = 150\n",
            "p = 0.4\n",
            "rbinom(n = 8, size = 150, prob = 0.4)\n\n",
            "# POISSON DISTRIBUTION\n",
            "# consider an average of 6 events, what is the probability of 5 events.\n",
            "lambda = 6\n",
            "x = 5\n",
            "prob = dpois(x, lambda)\n",
            "prob\n",
            "# plot\n",
            "plot(dpois(x, lambda), type = 'h', lwd = 2,\n",
            "     main = 'Poisson probability function',\n",
            "     ylab = 'P(X = x)', xlab = 'Number of events')\n\n",
            "# consider an average of 4 events, what is the probability of 3 or fewer events.\n",
            "lambda = 4\n",
            "x = 3\n",
            "prob = ppois(3, lambda)\n",
            "prob\n",
            "# consider an average of 6 events, what is the probability of 5-10 events.\n",
            "lambda = 6\n",
            "lower_bound = 5\n",
            "upper_bound = 10\n",
            "lb_prob = ppois(lower_bound, lambda)\n",
            "ub_prob = ppois(upper_bound, lambda)\n",
            "prob = ub_prob - lb_prob\n",
            "prob\n",
            "# rpois\n",
            "set.seed(10)\n",
            "prob = rpois(10, lambda = 4)\n",
            "prob\n")
      } else if (x == "nd") {
        cat("# NORMAL DISTRIBUTION\n\n",
            "# dnorm() function in R programming measures the density function of distribution\n\n",
            "# pnorm() function is the cumulative distribution function which measures\n",
            "# the probability that a random number X takes a value less than or equal to\n\n",
            "# dnorm(x, mean, sd)\n",
            "# pnorm(x, mean, sd)\n\n",
            "# If mu=450 and sigma=100 find\n",
            "# a--400 < x < 500,\n",
            "# b--x > 630,\n",
            "# c--x < 480,\n\n",
            "# a--pnorm(x, mean, sd) mean=450, sd=100\n",
            "pnorm(500, 450, 100) - pnorm(400, 450, 100)  # probability of 500 - probability of 400\n",
            "# b--pnorm(x, mean, sd) mean=450, sd=100, x > 630\n",
            "pnorm(630, 450, 100, lower.tail = FALSE)\n",
            "# c--pnorm(x, mean, sd) mean=450, sd=100, x < 480\n",
            "pnorm(480 - 1, 450, 100, lower.tail = TRUE)\n\n",
            "# plotting\n",
            "x = seq(-10, 10, by = 0.1)\n",
            "y = dnorm(x, mean = 2.5, sd = 0.5)\n\n",
            "plot(x, y, type = 'l', col = 'blue', main = 'Normal distribution')\n\n",
            "# plotting\n",
            "x = seq(-10, 10, by = 0.1)\n",
            "y = pnorm(x, mean = 2.5, sd = 0.5)\n\n",
            "plot(x, y, type = 'l', col = 'blue', main = 'Normal distribution')\n")
      } else if (x == "tt") {
        cat("# One-sample t-test--Tests whether a population mean is hypothesized to be significantly different from the sample mean.\n",
            "# (Two-tailed T-Test)\n",
            "# H0 – No Significant difference in the sample mean & population mean.\n",
            "# H1 – There is Significant difference in sample mean and population mean.\n",
            "# H0 – μ = xbar\n",
            "# H1 - μ ≠ xbar\n\n",
            "# One -Tail (Left tailed and Right tailed t-test)\n",
            "# H0 – μ  ≥ xbar\n",
            "# H1 - μ  < xbar\n\n",
            "# Example(Two tailed )\n",
            "# H0 – There is no Significant difference in the mean IQ of sample & population.\n",
            "# H1 - There is Significant difference in the mean IQ of sample & population.\n",
            "Iq <- c(109, 112, 106, 110, 108, 115, 99, 108, 104, 111)\n",
            "hyp_mean = 100 # hypothesized mean\n",
            "ttest_rest = t.test(Iq, mu = hyp_mean, alpha = 0.05, alternate = 'two.sided')\n",
            "ttest_rest\n\n",
            "# Two-sample t-test--Determines whether there is a significant difference between the two groups’ means.\n",
            "# H0 – There is no significant difference in mean of group1 and group2\n",
            "# H1 - There is significant difference in mean of group1 and group2\n",
            "#\n",
            "Wt <- c(67, 58, 54, 78, 80, 63, 52, 50, 76, 69, 72, 51, 73, 65)\n",
            "Gender <- c('M', 'F', 'F', 'M', 'F', 'F', 'F', 'M', 'M', 'M', 'M', 'F', 'M', 'M')\n",
            "Gender <- factor(Gender)\n",
            "# test for normality\n",
            "shapiro.test(Wt)\n",
            "# For Significant Outliers\n",
            "boxplot(Wt ~ Gender)\n",
            "# Homogeneity of Variance\n",
            "# Levene’s Test\n",
            "install.packages('car')\n",
            "library(car)\n",
            "leveneTest(Wt ~ Gender)\n",
            "t.test(DV ~ IV, alpha, alternative)\n",
            "t.test(Wt ~ Gender, alpha = 0.05, alternative = 'two.sided')\n\n",
            "# random normal variable\n",
            "set.seed(123)\n",
            "g1 = rnorm(30, mean = 25, sd = 5)\n",
            "g2 = rnorm(30, mean = 30, sd = 5)\n",
            "t.test(g1, g2)\n\n",
            "# Paired sample t-test--Tests hypotheses to determine if the mean difference between the paired samples differs noticeably from zero.\n",
            "# • H0: No difference in mean\n",
            "# • H3: The two means are different\n",
            "#\n",
            "# eg:---\n",
            "set.seed(123)\n",
            "# sales before the program\n",
            "sales_before <- rnorm(7, mean = 50000, sd = 50)\n",
            "# sales after the program.This has a higher mean\n",
            "sales_after <- rnorm(7, mean = 50075, sd = 50)\n",
            "# draw the distribution\n",
            "t.test(sales_before, sales_after, var.equal = TRUE)\n",
            "# You obtained a p-value of 0.04606, lower than the threshold of 0.05.\n",
            "# You conclude the averages of the two groups are significantly different.\n",
            "# The program improves the sales of shops.\n",
            "#\n",
            "# Data in two numeric vectors\n",
            "# Weight of the mice before treatment\n",
            "before <- c(200.1, 190.9, 192.7, 213, 241.4, 196.9, 172.2, 185.5, 205.2, 193.7) # Weight of the mice after treatment\n",
            "after <- c(392.9, 393.2, 345.1, 393, 434, 427.9, 422, 383.9, 392.3, 352.2)\n",
            "# Create a data frame\n",
            "my_data <- data.frame(group = rep(c('before', 'after'), each = 10), weight = c(before, after))\n",
            "install.packages('PairedData')\n",
            "# Subset weight data before treatment\n",
            "before <- subset(my_data, group == 'before', weight,\n",
            "                 drop = TRUE)\n",
            "# subset weight data after treatment\n",
            "after <- subset(my_data, group == 'after', weight,\n",
            "                drop = TRUE)\n",
            "d <- with(my_data, weight[group == 'before'] - weight[group == 'after'])\n",
            "# Shapiro-Wilk normality test for the differences\n",
            "shapiro.test(d)\n",
            "# => p-value = 0.6141\n",
            "res <- t.test(before, after)\n",
            "res\n\n",
            "# CHi-SQuare\n",
            "#\n",
            "# eg1\n",
            "# H0: No significant relationship.\n",
            "# H3: significant relationship.\n",
            "data('mtcars')\n",
            "table(mtcars$carb, mtcars$cyl) # Author DataFlair\n",
            "chisq.test(mtcars$carb, mtcars$cyl)\n",
            "# We have a high chi-squared value and a p-value of less than 0.05 significance level.\n",
            "# So we reject the null hypothesis and conclude that carb and cyl have a significant relationship.\n",
            "#\n",
            "# eg2\n",
            "# Load the library.\n",
            "library('MASS')\n",
            "# Create a data frame from the main data set.\n",
            "car.data <- data.frame(Cars93$AirBags, Cars93$Type)\n",
            "# Create a table with the needed variables.\n",
            "car.data = table(Cars93$AirBags, Cars93$Type)\n",
            "print(car.data)\n",
            "# Perform the Chi-Square test.\n",
            "print(chisq.test(car.data))\n",
            "# The result shows the p-value of less than 0.05 which indicates a strong correlation\n",
            "#\n",
            "# eg3\n",
            "# we collected wild tulips and found that 81 were red, 50 were yellow and 27 were white.\n",
            "# 1. Question 1:\n",
            "# Are these colors equally common?\n",
            "  # If these colors were equally distributed, the expected proportion would be 1/3 for each of the color.\n",
            "# 2. Question 2:\n",
            "  # Suppose that, in the region where you collected the data, the ratio of red, yellow, and white tulip is 3:2:1 (3+2+1 = 6).\n",
            "  # This means that the expected proportion is:\n",
            "  # • 3/6 (= 1/2) for red\n",
            "  # • 2/6 ( = 1/3) for yellow\n",
            "  # • 1/6 for white\n",
            "# We want to know if there is any significant difference between the observed proportions and the expected proportions.\n",
            "# chisq.test(x, p)\n",
            "# • x: a numeric vector\n",
            "# • p: a vector of probabilities of the same length of x.\n",
            "#\n",
            "# Q1-ans\n",
            "tulip <- c(81, 50, 27)\n",
            "res <- chisq.test(tulip, p = c(1/3, 1/3, 1/3))\n",
            "res\n",
            "# The p-value of the test is 8.80310^{-7}, which is less than the significance level alpha = 0.05.\n",
            "# We can conclude that the colors are significantly not commonly distributed\n",
            "#\n",
            "# Q2-ans\n",
            "tulip <- c(81, 50, 27)\n",
            "res <- chisq.test(tulip, p = c(1/2, 1/3, 1/6))\n",
            "res\n",
            "# The p-value of the test is 0.9037, which is greater than the significance level alpha = 0.05.\n",
            "# We can conclude that the observed proportions are not significantly different from the expected proportions.\n")
      } else if (x == "an") {
        cat("# ANOVA\n",
            "# eg1\n",
            "# H0: There is no significant difference between weight and group\n",
            "# H1: There is a significant difference between weight and group\n",
            "data = PlantGrowth\n",
            "res.aov = aov(weight ~ group, data = data)\n",
            "summary(res.aov)\n",
            "# We fail to accept H0\n\n",
            "# The mtcars(motor trend car road test) dataset is used which consists of 32 car brands and 11 attributes.\n",
            "# The dataset comes preinstalled in the dplyr package in R.\n",
            "# Performing One Way ANOVA\n",
            "# • H0 = mu = mu01 = mu02 (There is no difference between the average displacement for different gears)\n",
            "# • H1 = Not all means are equal.\n",
            "mtcars_aov <- aov(mtcars$disp ~ factor(mtcars$gear))\n",
            "summary(mtcars_aov)\n",
            "# We fail to accept H0\n\n",
            "# eg3\n",
            "# H0: There is no significant difference\n",
            "# H1: There is a significant difference\n",
            "data = c(6, 7, 3, 8, 5, 5, 3, 7, 5, 4, 3, 4)\n",
            "land = factor(c('A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'c', 'c', 'c', 'c'))\n",
            "model = aov(data ~ land)\n",
            "summary(model)\n\n",
            "# Performing Two Way ANOVA\n",
            "# H0: The means are equal for both variables (i.e., factor variable)\n",
            "# H1: The means are different for both variables\n\n",
            "# 1\n",
            "mtcars_aov2 = aov(mtcars$disp ~ factor(mtcars$gear) + factor(mtcars$am))\n",
            "summary(mtcars_aov2)\n\n",
            "# 2\n",
            "df = read.csv('C:/Users/Akanksha/Downloads/crop.data.xlsx - in.csv')\n",
            "df$density = factor(df$density)\n",
            "df$block = factor(df$block)\n",
            "df$fertilizer = factor(df$fertilizer)\n",
            "res = aov(yield ~ density + fertilizer, data = df)\n",
            "summary(res)\n",
            "res1 = aov(yield ~ density + block, data = df)\n",
            "summary(res1)\n")
      } else if (x == "st") {
        cat("# Signed test\n",
            "# Example 1\n",
            "# Create a vector of data \n",
            "data <- c(-1, 2, -3, 4, -5, 6, -7, 8) \n",
            "# Perform sign test using the binomial test function \n",
            "binom_test_result <- binom.test(sum(data > 0), length(data), p=0.5, alternative='two.sided') \n",
            "# View the results \n",
            "print(binom_test_result)\n\n",
            "# Wide data\n",
            "set.seed(1234)\n",
            "my_data <- data.frame(name = paste0(rep('M_', 10), 1:10),\n",
            "                      weight = round(rnorm(10, 20, 2), 1))\n",
            "head(my_data, 10)\n",
            "# Statistical summaries of weight\n",
            "summary(my_data$weight)\n",
            "# One-sample wilcoxon test\n",
            "res <- wilcox.test(my_data$weight, mu = 25)\n",
            "res\n",
            "# Print only the p-value\n",
            "res$p.value\n",
            "# SignTest\n",
            "SignTest(Data$Likert, mu = 3)\n")
      } else {
        cat("Input is\n",
            'ct = "central tendency"\n',
            'df = "Data entry and presentation"\n',
            'mo = "mathematical operation"\n',
            'mx = "Matrix and dataframe ops and features"\n',
            'co = "Pearson correlation"\n',
            'cp = "conditional probability"\n',
            'bp = "binomial and possion"\n',
            'nd = "normal distribution"\n',
            'tt = "t-test"\n',
            'an = "ANOVA"\n',
            'st = "Signed test"\n'
        )

      }
    } else {
      cat("Input is not character\n")
    }
  }
}
